OBJS	= instruction_pass2.o operand.o
SOURCE	= instruction_pass2.c operand.c
HEADER	= instruction_pass2.h operand.h
OUT	= instruction
CC	 = gcc
FLAGS	 = -g -c -Wall
LFLAGS	 = 

all: $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

instruction_pass2.o: instruction_pass2.c
	$(CC) $(FLAGS) instruction_pass2.c 

operand.o: operand.c
	$(CC) $(FLAGS) operand.c 


clean:
	rm -f $(OBJS) $(OUT)
